version: "3"

services:
  nodecg:
    image: ghcr.io/nodecg/nodecg:2
    user: root
    command: sh -c "npm i --omit=dev && node --enable-source-maps ../.."
    working_dir: /opt/nodecg/bundles/warhammer-40k
    init: true
    ports:
      - 9090:9090
    volumes:
      - nodecg_db:/opt/nodecg/db
      - nodecg_assets:/opt/nodecg/assets
      - node_modules:/opt/nodecg/bundles/warhammer-40k/node_modules
      - ./cfg:/opt/nodecg/cfg:ro
      - ./package.json:/opt/nodecg/bundles/warhammer-40k/package.json:ro
      - ./package-lock.json:/opt/nodecg/bundles/warhammer-40k/package-lock.json
      - ./dashboard:/opt/nodecg/bundles/warhammer-40k/dashboard:ro
      - ./extension:/opt/nodecg/bundles/warhammer-40k/extension:ro
      - ./graphics:/opt/nodecg/bundles/warhammer-40k/graphics:ro
      - ./schemas:/opt/nodecg/bundles/warhammer-40k/schemas:ro
      - ./spotify-callback:/opt/nodecg/bundles/warhammer-40k/spotify-callback:ro
      - ./src:/opt/nodecg/bundles/warhammer-40k/src:ro
      - ./shared:/opt/nodecg/bundles/warhammer-40k/shared:ro

volumes:
  nodecg_db:
  nodecg_assets:
  node_modules:
